import { useState } from 'react';
import { useNavigate, useLocation } from 'react-router-dom';
import { motion } from 'framer-motion';
import { useForm } from 'react-hook-form';
import { zodResolver } from '@hookform/resolvers/zod';
import { z } from 'zod';
import { supabase } from '@/integrations/supabase/client';
import { toast } from 'sonner';
import { Loader2, ArrowLeft, Package, Truck, CreditCard } from 'lucide-react';
import { SEOHead } from '@/components/seo/SEOHead';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Textarea } from '@/components/ui/textarea';
import { Label } from '@/components/ui/label';
import { RadioGroup, RadioGroupItem } from '@/components/ui/radio-group';
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select';

const checkoutSchema = z.object({
  customer_name: z.string().min(2, 'Name must be at least 2 characters').max(100),
  customer_email: z.string().email('Invalid email address').max(255),
  customer_phone: z.string().min(10, 'Phone number is required').max(20),
  shipping_address: z.string().min(10, 'Address must be at least 10 characters').max(500),
  shipping_city: z.string().min(2, 'City is required').max(100),
  shipping_district: z.string().min(2, 'District is required').max(100),
  notes: z.string().max(500).optional(),
  payment_method: z.enum(['cod', 'bkash', 'nagad']),
});

type CheckoutFormData = z.infer<typeof checkoutSchema>;

interface CartItem {
  id: string;
  name: string;
  price: number;
  image: string;
  quantity: number;
}

const districts = [
  'Dhaka', 'Chittagong', 'Rajshahi', 'Khulna', 'Sylhet', 'Barisal', 'Rangpur', 'Mymensingh',
  'Comilla', 'Gazipur', 'Narayanganj', 'Bogra', 'Cox\'s Bazar', 'Jessore', 'Dinajpur',
  'Brahmanbaria', 'Tangail', 'Jamalpur', 'Narsingdi', 'Savar', 'Tongi'
];

export default function Checkout() {
  const navigate = useNavigate();
  const location = useLocation();
  const [loading, setLoading] = useState(false);
  
  // Get cart items from location state
  const cartItems: CartItem[] = location.state?.cartItems || [];
  const totalAmount = location.state?.totalAmount || 0;
  
  const shippingCost = 100; // Fixed shipping cost in BDT
  const grandTotal = totalAmount + shippingCost;

  const {
    register,
    handleSubmit,
    setValue,
    watch,
    formState: { errors },
  } = useForm<CheckoutFormData>({
    resolver: zodResolver(checkoutSchema),
    defaultValues: {
      payment_method: 'cod',
    },
  });

  const onSubmit = async (data: CheckoutFormData) => {
    if (cartItems.length === 0) {
      toast.error('Your cart is empty');
      return;
    }

    setLoading(true);
    try {
      // Create order - order_number is auto-generated by trigger
      const { data: order, error: orderError } = await supabase
        .from('orders')
        .insert([{
          customer_name: data.customer_name,
          customer_email: data.customer_email,
          customer_phone: data.customer_phone,
          shipping_address: data.shipping_address,
          shipping_city: data.shipping_city,
          shipping_district: data.shipping_district,
          notes: data.notes || null,
          payment_method: data.payment_method,
          total_amount: grandTotal,
          shipping_cost: shippingCost,
          status: 'pending',
          payment_status: 'pending',
        } as any])
        .select()
        .single();

      if (orderError) throw orderError;

      // Create order items
      const orderItems = cartItems.map((item) => ({
        order_id: order.id,
        product_id: item.id,
        product_name: item.name,
        quantity: item.quantity,
        unit_price: item.price,
        total_price: item.price * item.quantity,
      }));

      const { error: itemsError } = await supabase
        .from('order_items')
        .insert(orderItems);

      if (itemsError) throw itemsError;

      toast.success('Order placed successfully!');
      navigate('/order-success', { 
        state: { 
          orderNumber: order.order_number,
          totalAmount: grandTotal,
        } 
      });
    } catch (error: any) {
      toast.error(error.message || 'Failed to place order');
    } finally {
      setLoading(false);
    }
  };

  if (cartItems.length === 0) {
    return (
      <>
        <SEOHead title="Checkout" description="Complete your order" />
        <div className="min-h-screen flex items-center justify-center px-6">
          <div className="text-center">
            <Package className="w-16 h-16 mx-auto mb-4 text-muted-foreground" />
            <h1 className="text-2xl font-light mb-2">Your cart is empty</h1>
            <p className="text-muted-foreground mb-6">Add some products before checking out</p>
            <Button onClick={() => navigate('/shop')}>
              Continue Shopping
            </Button>
          </div>
        </div>
      </>
    );
  }

  return (
    <>
      <SEOHead 
        title="Checkout" 
        description="Complete your Sharee order - secure checkout" 
      />

      <div className="min-h-screen bg-secondary/20 py-12">
        <div className="max-w-6xl mx-auto px-6">
          <Button
            variant="ghost"
            onClick={() => navigate('/shop')}
            className="mb-6"
          >
            <ArrowLeft className="w-4 h-4 mr-2" />
            Back to Shop
          </Button>

          <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
            {/* Checkout Form */}
            <motion.div
              className="lg:col-span-2"
              initial={{ opacity: 0, x: -20 }}
              animate={{ opacity: 1, x: 0 }}
              transition={{ duration: 0.5 }}
            >
              <div className="bg-background rounded-2xl p-6 md:p-8 shadow-sm">
                <h1 className="text-2xl font-light mb-6">Checkout</h1>

                <form onSubmit={handleSubmit(onSubmit)} className="space-y-6">
                  {/* Contact Information */}
                  <div className="space-y-4">
                    <h2 className="text-lg font-medium flex items-center gap-2">
                      <Package className="w-5 h-5" />
                      Contact Information
                    </h2>
                    
                    <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                      <div className="space-y-2">
                        <Label htmlFor="customer_name">Full Name *</Label>
                        <Input
                          id="customer_name"
                          {...register('customer_name')}
                          placeholder="Your full name"
                        />
                        {errors.customer_name && (
                          <p className="text-sm text-destructive">{errors.customer_name.message}</p>
                        )}
                      </div>

                      <div className="space-y-2">
                        <Label htmlFor="customer_phone">Phone Number *</Label>
                        <Input
                          id="customer_phone"
                          {...register('customer_phone')}
                          placeholder="01XXXXXXXXX"
                        />
                        {errors.customer_phone && (
                          <p className="text-sm text-destructive">{errors.customer_phone.message}</p>
                        )}
                      </div>
                    </div>

                    <div className="space-y-2">
                      <Label htmlFor="customer_email">Email Address *</Label>
                      <Input
                        id="customer_email"
                        type="email"
                        {...register('customer_email')}
                        placeholder="your@email.com"
                      />
                      {errors.customer_email && (
                        <p className="text-sm text-destructive">{errors.customer_email.message}</p>
                      )}
                    </div>
                  </div>

                  {/* Shipping Information */}
                  <div className="space-y-4 pt-4 border-t">
                    <h2 className="text-lg font-medium flex items-center gap-2">
                      <Truck className="w-5 h-5" />
                      Shipping Address
                    </h2>

                    <div className="space-y-2">
                      <Label htmlFor="shipping_address">Full Address *</Label>
                      <Textarea
                        id="shipping_address"
                        {...register('shipping_address')}
                        rows={2}
                        placeholder="House no, Road no, Area name..."
                      />
                      {errors.shipping_address && (
                        <p className="text-sm text-destructive">{errors.shipping_address.message}</p>
                      )}
                    </div>

                    <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                      <div className="space-y-2">
                        <Label htmlFor="shipping_city">City *</Label>
                        <Input
                          id="shipping_city"
                          {...register('shipping_city')}
                          placeholder="City name"
                        />
                        {errors.shipping_city && (
                          <p className="text-sm text-destructive">{errors.shipping_city.message}</p>
                        )}
                      </div>

                      <div className="space-y-2">
                        <Label>District *</Label>
                        <Select
                          onValueChange={(value) => setValue('shipping_district', value)}
                        >
                          <SelectTrigger>
                            <SelectValue placeholder="Select district" />
                          </SelectTrigger>
                          <SelectContent>
                            {districts.map((district) => (
                              <SelectItem key={district} value={district}>
                                {district}
                              </SelectItem>
                            ))}
                          </SelectContent>
                        </Select>
                        {errors.shipping_district && (
                          <p className="text-sm text-destructive">{errors.shipping_district.message}</p>
                        )}
                      </div>
                    </div>

                    <div className="space-y-2">
                      <Label htmlFor="notes">Order Notes (Optional)</Label>
                      <Textarea
                        id="notes"
                        {...register('notes')}
                        rows={2}
                        placeholder="Any special instructions..."
                      />
                    </div>
                  </div>

                  {/* Payment Method */}
                  <div className="space-y-4 pt-4 border-t">
                    <h2 className="text-lg font-medium flex items-center gap-2">
                      <CreditCard className="w-5 h-5" />
                      Payment Method
                    </h2>

                    <RadioGroup
                      defaultValue="cod"
                      onValueChange={(value) => setValue('payment_method', value as any)}
                      className="grid grid-cols-1 md:grid-cols-3 gap-4"
                    >
                      <div className="flex items-center space-x-2 border rounded-lg p-4 cursor-pointer hover:border-primary transition-colors">
                        <RadioGroupItem value="cod" id="cod" />
                        <Label htmlFor="cod" className="cursor-pointer flex-1">
                          <span className="font-medium">Cash on Delivery</span>
                          <span className="block text-sm text-muted-foreground">Pay when you receive</span>
                        </Label>
                      </div>
                      <div className="flex items-center space-x-2 border rounded-lg p-4 cursor-pointer hover:border-primary transition-colors">
                        <RadioGroupItem value="bkash" id="bkash" />
                        <Label htmlFor="bkash" className="cursor-pointer flex-1">
                          <span className="font-medium">bKash</span>
                          <span className="block text-sm text-muted-foreground">Mobile banking</span>
                        </Label>
                      </div>
                      <div className="flex items-center space-x-2 border rounded-lg p-4 cursor-pointer hover:border-primary transition-colors">
                        <RadioGroupItem value="nagad" id="nagad" />
                        <Label htmlFor="nagad" className="cursor-pointer flex-1">
                          <span className="font-medium">Nagad</span>
                          <span className="block text-sm text-muted-foreground">Mobile banking</span>
                        </Label>
                      </div>
                    </RadioGroup>
                  </div>

                  <Button
                    type="submit"
                    size="lg"
                    className="w-full"
                    disabled={loading}
                  >
                    {loading && <Loader2 className="w-4 h-4 mr-2 animate-spin" />}
                    Place Order - ৳{grandTotal.toLocaleString()}
                  </Button>
                </form>
              </div>
            </motion.div>

            {/* Order Summary */}
            <motion.div
              initial={{ opacity: 0, x: 20 }}
              animate={{ opacity: 1, x: 0 }}
              transition={{ duration: 0.5, delay: 0.1 }}
            >
              <div className="bg-background rounded-2xl p-6 shadow-sm sticky top-24">
                <h2 className="text-lg font-medium mb-4">Order Summary</h2>

                <div className="space-y-4 mb-6">
                  {cartItems.map((item) => (
                    <div key={item.id} className="flex gap-3">
                      <img
                        src={item.image}
                        alt={item.name}
                        className="w-16 h-16 object-cover rounded-lg"
                      />
                      <div className="flex-1">
                        <p className="font-medium text-sm line-clamp-1">{item.name}</p>
                        <p className="text-sm text-muted-foreground">
                          Qty: {item.quantity}
                        </p>
                        <p className="text-sm font-medium">
                          ৳{(item.price * item.quantity).toLocaleString()}
                        </p>
                      </div>
                    </div>
                  ))}
                </div>

                <div className="border-t pt-4 space-y-2">
                  <div className="flex justify-between text-sm">
                    <span className="text-muted-foreground">Subtotal</span>
                    <span>৳{totalAmount.toLocaleString()}</span>
                  </div>
                  <div className="flex justify-between text-sm">
                    <span className="text-muted-foreground">Shipping</span>
                    <span>৳{shippingCost.toLocaleString()}</span>
                  </div>
                  <div className="flex justify-between font-medium text-lg pt-2 border-t">
                    <span>Total</span>
                    <span>৳{grandTotal.toLocaleString()}</span>
                  </div>
                </div>
              </div>
            </motion.div>
          </div>
        </div>
      </div>
    </>
  );
}
